// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: herald/mesh/messages/mesh.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_herald_2fmesh_2fmessages_2fmesh_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_herald_2fmesh_2fmessages_2fmesh_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_herald_2fmesh_2fmessages_2fmesh_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto;
namespace herald {
namespace mesh {
namespace messages {
class MeshGet;
struct MeshGetDefaultTypeInternal;
extern MeshGetDefaultTypeInternal _MeshGet_default_instance_;
class MeshPublish;
struct MeshPublishDefaultTypeInternal;
extern MeshPublishDefaultTypeInternal _MeshPublish_default_instance_;
class MeshSend;
struct MeshSendDefaultTypeInternal;
extern MeshSendDefaultTypeInternal _MeshSend_default_instance_;
class MeshSet;
struct MeshSetDefaultTypeInternal;
extern MeshSetDefaultTypeInternal _MeshSet_default_instance_;
class MeshSubscribe;
struct MeshSubscribeDefaultTypeInternal;
extern MeshSubscribeDefaultTypeInternal _MeshSubscribe_default_instance_;
class MeshUnsubscribe;
struct MeshUnsubscribeDefaultTypeInternal;
extern MeshUnsubscribeDefaultTypeInternal _MeshUnsubscribe_default_instance_;
}  // namespace messages
}  // namespace mesh
}  // namespace herald
PROTOBUF_NAMESPACE_OPEN
template<> ::herald::mesh::messages::MeshGet* Arena::CreateMaybeMessage<::herald::mesh::messages::MeshGet>(Arena*);
template<> ::herald::mesh::messages::MeshPublish* Arena::CreateMaybeMessage<::herald::mesh::messages::MeshPublish>(Arena*);
template<> ::herald::mesh::messages::MeshSend* Arena::CreateMaybeMessage<::herald::mesh::messages::MeshSend>(Arena*);
template<> ::herald::mesh::messages::MeshSet* Arena::CreateMaybeMessage<::herald::mesh::messages::MeshSet>(Arena*);
template<> ::herald::mesh::messages::MeshSubscribe* Arena::CreateMaybeMessage<::herald::mesh::messages::MeshSubscribe>(Arena*);
template<> ::herald::mesh::messages::MeshUnsubscribe* Arena::CreateMaybeMessage<::herald::mesh::messages::MeshUnsubscribe>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace herald {
namespace mesh {
namespace messages {

// ===================================================================

class MeshGet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.MeshGet) */ {
 public:
  inline MeshGet() : MeshGet(nullptr) {}
  ~MeshGet() override;
  explicit PROTOBUF_CONSTEXPR MeshGet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MeshGet(const MeshGet& from);
  MeshGet(MeshGet&& from) noexcept
    : MeshGet() {
    *this = ::std::move(from);
  }

  inline MeshGet& operator=(const MeshGet& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshGet& operator=(MeshGet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshGet& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshGet* internal_default_instance() {
    return reinterpret_cast<const MeshGet*>(
               &_MeshGet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MeshGet& a, MeshGet& b) {
    a.Swap(&b);
  }
  inline void Swap(MeshGet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshGet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshGet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MeshGet>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MeshGet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.MeshGet";
  }
  protected:
  explicit MeshGet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kModelIdFieldNumber = 2,
    kFieldIdFieldNumber = 3,
  };
  // uint32 nodeId = 1;
  void clear_nodeid();
  uint32_t nodeid() const;
  void set_nodeid(uint32_t value);
  private:
  uint32_t _internal_nodeid() const;
  void _internal_set_nodeid(uint32_t value);
  public:

  // uint32 modelId = 2;
  void clear_modelid();
  uint32_t modelid() const;
  void set_modelid(uint32_t value);
  private:
  uint32_t _internal_modelid() const;
  void _internal_set_modelid(uint32_t value);
  public:

  // uint32 fieldId = 3;
  void clear_fieldid();
  uint32_t fieldid() const;
  void set_fieldid(uint32_t value);
  private:
  uint32_t _internal_fieldid() const;
  void _internal_set_fieldid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.MeshGet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t nodeid_;
    uint32_t modelid_;
    uint32_t fieldid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto;
};
// -------------------------------------------------------------------

class MeshSet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.MeshSet) */ {
 public:
  inline MeshSet() : MeshSet(nullptr) {}
  ~MeshSet() override;
  explicit PROTOBUF_CONSTEXPR MeshSet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MeshSet(const MeshSet& from);
  MeshSet(MeshSet&& from) noexcept
    : MeshSet() {
    *this = ::std::move(from);
  }

  inline MeshSet& operator=(const MeshSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshSet& operator=(MeshSet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshSet& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshSet* internal_default_instance() {
    return reinterpret_cast<const MeshSet*>(
               &_MeshSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MeshSet& a, MeshSet& b) {
    a.Swap(&b);
  }
  inline void Swap(MeshSet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshSet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshSet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MeshSet>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MeshSet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.MeshSet";
  }
  protected:
  explicit MeshSet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kModelIdFieldNumber = 2,
    kFieldIdFieldNumber = 3,
    kReplyFieldNumber = 4,
  };
  // uint32 nodeId = 1;
  void clear_nodeid();
  uint32_t nodeid() const;
  void set_nodeid(uint32_t value);
  private:
  uint32_t _internal_nodeid() const;
  void _internal_set_nodeid(uint32_t value);
  public:

  // uint32 modelId = 2;
  void clear_modelid();
  uint32_t modelid() const;
  void set_modelid(uint32_t value);
  private:
  uint32_t _internal_modelid() const;
  void _internal_set_modelid(uint32_t value);
  public:

  // uint32 fieldId = 3;
  void clear_fieldid();
  uint32_t fieldid() const;
  void set_fieldid(uint32_t value);
  private:
  uint32_t _internal_fieldid() const;
  void _internal_set_fieldid(uint32_t value);
  public:

  // bool reply = 4;
  void clear_reply();
  bool reply() const;
  void set_reply(bool value);
  private:
  bool _internal_reply() const;
  void _internal_set_reply(bool value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.MeshSet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t nodeid_;
    uint32_t modelid_;
    uint32_t fieldid_;
    bool reply_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto;
};
// -------------------------------------------------------------------

class MeshSubscribe final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.MeshSubscribe) */ {
 public:
  inline MeshSubscribe() : MeshSubscribe(nullptr) {}
  ~MeshSubscribe() override;
  explicit PROTOBUF_CONSTEXPR MeshSubscribe(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MeshSubscribe(const MeshSubscribe& from);
  MeshSubscribe(MeshSubscribe&& from) noexcept
    : MeshSubscribe() {
    *this = ::std::move(from);
  }

  inline MeshSubscribe& operator=(const MeshSubscribe& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshSubscribe& operator=(MeshSubscribe&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshSubscribe& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshSubscribe* internal_default_instance() {
    return reinterpret_cast<const MeshSubscribe*>(
               &_MeshSubscribe_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MeshSubscribe& a, MeshSubscribe& b) {
    a.Swap(&b);
  }
  inline void Swap(MeshSubscribe* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshSubscribe* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshSubscribe* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MeshSubscribe>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MeshSubscribe* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.MeshSubscribe";
  }
  protected:
  explicit MeshSubscribe(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kModelIdFieldNumber = 2,
    kActivityIdFieldNumber = 3,
  };
  // uint32 nodeId = 1;
  void clear_nodeid();
  uint32_t nodeid() const;
  void set_nodeid(uint32_t value);
  private:
  uint32_t _internal_nodeid() const;
  void _internal_set_nodeid(uint32_t value);
  public:

  // uint32 modelId = 2;
  void clear_modelid();
  uint32_t modelid() const;
  void set_modelid(uint32_t value);
  private:
  uint32_t _internal_modelid() const;
  void _internal_set_modelid(uint32_t value);
  public:

  // uint32 activityId = 3;
  void clear_activityid();
  uint32_t activityid() const;
  void set_activityid(uint32_t value);
  private:
  uint32_t _internal_activityid() const;
  void _internal_set_activityid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.MeshSubscribe)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t nodeid_;
    uint32_t modelid_;
    uint32_t activityid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto;
};
// -------------------------------------------------------------------

class MeshUnsubscribe final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.MeshUnsubscribe) */ {
 public:
  inline MeshUnsubscribe() : MeshUnsubscribe(nullptr) {}
  ~MeshUnsubscribe() override;
  explicit PROTOBUF_CONSTEXPR MeshUnsubscribe(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MeshUnsubscribe(const MeshUnsubscribe& from);
  MeshUnsubscribe(MeshUnsubscribe&& from) noexcept
    : MeshUnsubscribe() {
    *this = ::std::move(from);
  }

  inline MeshUnsubscribe& operator=(const MeshUnsubscribe& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshUnsubscribe& operator=(MeshUnsubscribe&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshUnsubscribe& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshUnsubscribe* internal_default_instance() {
    return reinterpret_cast<const MeshUnsubscribe*>(
               &_MeshUnsubscribe_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MeshUnsubscribe& a, MeshUnsubscribe& b) {
    a.Swap(&b);
  }
  inline void Swap(MeshUnsubscribe* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshUnsubscribe* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshUnsubscribe* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MeshUnsubscribe>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MeshUnsubscribe* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.MeshUnsubscribe";
  }
  protected:
  explicit MeshUnsubscribe(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kModelIdFieldNumber = 2,
    kActivityIdFieldNumber = 3,
  };
  // uint32 nodeId = 1;
  void clear_nodeid();
  uint32_t nodeid() const;
  void set_nodeid(uint32_t value);
  private:
  uint32_t _internal_nodeid() const;
  void _internal_set_nodeid(uint32_t value);
  public:

  // uint32 modelId = 2;
  void clear_modelid();
  uint32_t modelid() const;
  void set_modelid(uint32_t value);
  private:
  uint32_t _internal_modelid() const;
  void _internal_set_modelid(uint32_t value);
  public:

  // uint32 activityId = 3;
  void clear_activityid();
  uint32_t activityid() const;
  void set_activityid(uint32_t value);
  private:
  uint32_t _internal_activityid() const;
  void _internal_set_activityid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.MeshUnsubscribe)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t nodeid_;
    uint32_t modelid_;
    uint32_t activityid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto;
};
// -------------------------------------------------------------------

class MeshPublish final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.MeshPublish) */ {
 public:
  inline MeshPublish() : MeshPublish(nullptr) {}
  ~MeshPublish() override;
  explicit PROTOBUF_CONSTEXPR MeshPublish(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MeshPublish(const MeshPublish& from);
  MeshPublish(MeshPublish&& from) noexcept
    : MeshPublish() {
    *this = ::std::move(from);
  }

  inline MeshPublish& operator=(const MeshPublish& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshPublish& operator=(MeshPublish&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshPublish& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshPublish* internal_default_instance() {
    return reinterpret_cast<const MeshPublish*>(
               &_MeshPublish_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(MeshPublish& a, MeshPublish& b) {
    a.Swap(&b);
  }
  inline void Swap(MeshPublish* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshPublish* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshPublish* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MeshPublish>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MeshPublish* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.MeshPublish";
  }
  protected:
  explicit MeshPublish(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 3,
    kTopicIdFieldNumber = 1,
  };
  // repeated bytes message = 3;
  int message_size() const;
  private:
  int _internal_message_size() const;
  public:
  void clear_message();
  const std::string& message(int index) const;
  std::string* mutable_message(int index);
  void set_message(int index, const std::string& value);
  void set_message(int index, std::string&& value);
  void set_message(int index, const char* value);
  void set_message(int index, const void* value, size_t size);
  std::string* add_message();
  void add_message(const std::string& value);
  void add_message(std::string&& value);
  void add_message(const char* value);
  void add_message(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& message() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_message();
  private:
  const std::string& _internal_message(int index) const;
  std::string* _internal_add_message();
  public:

  // uint32 topicId = 1;
  void clear_topicid();
  uint32_t topicid() const;
  void set_topicid(uint32_t value);
  private:
  uint32_t _internal_topicid() const;
  void _internal_set_topicid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.MeshPublish)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> message_;
    uint32_t topicid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto;
};
// -------------------------------------------------------------------

class MeshSend final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.MeshSend) */ {
 public:
  inline MeshSend() : MeshSend(nullptr) {}
  ~MeshSend() override;
  explicit PROTOBUF_CONSTEXPR MeshSend(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MeshSend(const MeshSend& from);
  MeshSend(MeshSend&& from) noexcept
    : MeshSend() {
    *this = ::std::move(from);
  }

  inline MeshSend& operator=(const MeshSend& from) {
    CopyFrom(from);
    return *this;
  }
  inline MeshSend& operator=(MeshSend&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MeshSend& default_instance() {
    return *internal_default_instance();
  }
  static inline const MeshSend* internal_default_instance() {
    return reinterpret_cast<const MeshSend*>(
               &_MeshSend_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(MeshSend& a, MeshSend& b) {
    a.Swap(&b);
  }
  inline void Swap(MeshSend* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MeshSend* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MeshSend* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MeshSend>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MeshSend* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.MeshSend";
  }
  protected:
  explicit MeshSend(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 3,
    kNodeIdFieldNumber = 1,
    kModelIdFieldNumber = 2,
  };
  // repeated bytes message = 3;
  int message_size() const;
  private:
  int _internal_message_size() const;
  public:
  void clear_message();
  const std::string& message(int index) const;
  std::string* mutable_message(int index);
  void set_message(int index, const std::string& value);
  void set_message(int index, std::string&& value);
  void set_message(int index, const char* value);
  void set_message(int index, const void* value, size_t size);
  std::string* add_message();
  void add_message(const std::string& value);
  void add_message(std::string&& value);
  void add_message(const char* value);
  void add_message(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& message() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_message();
  private:
  const std::string& _internal_message(int index) const;
  std::string* _internal_add_message();
  public:

  // uint32 nodeId = 1;
  void clear_nodeid();
  uint32_t nodeid() const;
  void set_nodeid(uint32_t value);
  private:
  uint32_t _internal_nodeid() const;
  void _internal_set_nodeid(uint32_t value);
  public:

  // uint32 modelId = 2;
  void clear_modelid();
  uint32_t modelid() const;
  void set_modelid(uint32_t value);
  private:
  uint32_t _internal_modelid() const;
  void _internal_set_modelid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.MeshSend)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> message_;
    uint32_t nodeid_;
    uint32_t modelid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MeshGet

// uint32 nodeId = 1;
inline void MeshGet::clear_nodeid() {
  _impl_.nodeid_ = 0u;
}
inline uint32_t MeshGet::_internal_nodeid() const {
  return _impl_.nodeid_;
}
inline uint32_t MeshGet::nodeid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshGet.nodeId)
  return _internal_nodeid();
}
inline void MeshGet::_internal_set_nodeid(uint32_t value) {
  
  _impl_.nodeid_ = value;
}
inline void MeshGet::set_nodeid(uint32_t value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshGet.nodeId)
}

// uint32 modelId = 2;
inline void MeshGet::clear_modelid() {
  _impl_.modelid_ = 0u;
}
inline uint32_t MeshGet::_internal_modelid() const {
  return _impl_.modelid_;
}
inline uint32_t MeshGet::modelid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshGet.modelId)
  return _internal_modelid();
}
inline void MeshGet::_internal_set_modelid(uint32_t value) {
  
  _impl_.modelid_ = value;
}
inline void MeshGet::set_modelid(uint32_t value) {
  _internal_set_modelid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshGet.modelId)
}

// uint32 fieldId = 3;
inline void MeshGet::clear_fieldid() {
  _impl_.fieldid_ = 0u;
}
inline uint32_t MeshGet::_internal_fieldid() const {
  return _impl_.fieldid_;
}
inline uint32_t MeshGet::fieldid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshGet.fieldId)
  return _internal_fieldid();
}
inline void MeshGet::_internal_set_fieldid(uint32_t value) {
  
  _impl_.fieldid_ = value;
}
inline void MeshGet::set_fieldid(uint32_t value) {
  _internal_set_fieldid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshGet.fieldId)
}

// -------------------------------------------------------------------

// MeshSet

// uint32 nodeId = 1;
inline void MeshSet::clear_nodeid() {
  _impl_.nodeid_ = 0u;
}
inline uint32_t MeshSet::_internal_nodeid() const {
  return _impl_.nodeid_;
}
inline uint32_t MeshSet::nodeid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSet.nodeId)
  return _internal_nodeid();
}
inline void MeshSet::_internal_set_nodeid(uint32_t value) {
  
  _impl_.nodeid_ = value;
}
inline void MeshSet::set_nodeid(uint32_t value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSet.nodeId)
}

// uint32 modelId = 2;
inline void MeshSet::clear_modelid() {
  _impl_.modelid_ = 0u;
}
inline uint32_t MeshSet::_internal_modelid() const {
  return _impl_.modelid_;
}
inline uint32_t MeshSet::modelid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSet.modelId)
  return _internal_modelid();
}
inline void MeshSet::_internal_set_modelid(uint32_t value) {
  
  _impl_.modelid_ = value;
}
inline void MeshSet::set_modelid(uint32_t value) {
  _internal_set_modelid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSet.modelId)
}

// uint32 fieldId = 3;
inline void MeshSet::clear_fieldid() {
  _impl_.fieldid_ = 0u;
}
inline uint32_t MeshSet::_internal_fieldid() const {
  return _impl_.fieldid_;
}
inline uint32_t MeshSet::fieldid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSet.fieldId)
  return _internal_fieldid();
}
inline void MeshSet::_internal_set_fieldid(uint32_t value) {
  
  _impl_.fieldid_ = value;
}
inline void MeshSet::set_fieldid(uint32_t value) {
  _internal_set_fieldid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSet.fieldId)
}

// bool reply = 4;
inline void MeshSet::clear_reply() {
  _impl_.reply_ = false;
}
inline bool MeshSet::_internal_reply() const {
  return _impl_.reply_;
}
inline bool MeshSet::reply() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSet.reply)
  return _internal_reply();
}
inline void MeshSet::_internal_set_reply(bool value) {
  
  _impl_.reply_ = value;
}
inline void MeshSet::set_reply(bool value) {
  _internal_set_reply(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSet.reply)
}

// -------------------------------------------------------------------

// MeshSubscribe

// uint32 nodeId = 1;
inline void MeshSubscribe::clear_nodeid() {
  _impl_.nodeid_ = 0u;
}
inline uint32_t MeshSubscribe::_internal_nodeid() const {
  return _impl_.nodeid_;
}
inline uint32_t MeshSubscribe::nodeid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSubscribe.nodeId)
  return _internal_nodeid();
}
inline void MeshSubscribe::_internal_set_nodeid(uint32_t value) {
  
  _impl_.nodeid_ = value;
}
inline void MeshSubscribe::set_nodeid(uint32_t value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSubscribe.nodeId)
}

// uint32 modelId = 2;
inline void MeshSubscribe::clear_modelid() {
  _impl_.modelid_ = 0u;
}
inline uint32_t MeshSubscribe::_internal_modelid() const {
  return _impl_.modelid_;
}
inline uint32_t MeshSubscribe::modelid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSubscribe.modelId)
  return _internal_modelid();
}
inline void MeshSubscribe::_internal_set_modelid(uint32_t value) {
  
  _impl_.modelid_ = value;
}
inline void MeshSubscribe::set_modelid(uint32_t value) {
  _internal_set_modelid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSubscribe.modelId)
}

// uint32 activityId = 3;
inline void MeshSubscribe::clear_activityid() {
  _impl_.activityid_ = 0u;
}
inline uint32_t MeshSubscribe::_internal_activityid() const {
  return _impl_.activityid_;
}
inline uint32_t MeshSubscribe::activityid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSubscribe.activityId)
  return _internal_activityid();
}
inline void MeshSubscribe::_internal_set_activityid(uint32_t value) {
  
  _impl_.activityid_ = value;
}
inline void MeshSubscribe::set_activityid(uint32_t value) {
  _internal_set_activityid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSubscribe.activityId)
}

// -------------------------------------------------------------------

// MeshUnsubscribe

// uint32 nodeId = 1;
inline void MeshUnsubscribe::clear_nodeid() {
  _impl_.nodeid_ = 0u;
}
inline uint32_t MeshUnsubscribe::_internal_nodeid() const {
  return _impl_.nodeid_;
}
inline uint32_t MeshUnsubscribe::nodeid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshUnsubscribe.nodeId)
  return _internal_nodeid();
}
inline void MeshUnsubscribe::_internal_set_nodeid(uint32_t value) {
  
  _impl_.nodeid_ = value;
}
inline void MeshUnsubscribe::set_nodeid(uint32_t value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshUnsubscribe.nodeId)
}

// uint32 modelId = 2;
inline void MeshUnsubscribe::clear_modelid() {
  _impl_.modelid_ = 0u;
}
inline uint32_t MeshUnsubscribe::_internal_modelid() const {
  return _impl_.modelid_;
}
inline uint32_t MeshUnsubscribe::modelid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshUnsubscribe.modelId)
  return _internal_modelid();
}
inline void MeshUnsubscribe::_internal_set_modelid(uint32_t value) {
  
  _impl_.modelid_ = value;
}
inline void MeshUnsubscribe::set_modelid(uint32_t value) {
  _internal_set_modelid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshUnsubscribe.modelId)
}

// uint32 activityId = 3;
inline void MeshUnsubscribe::clear_activityid() {
  _impl_.activityid_ = 0u;
}
inline uint32_t MeshUnsubscribe::_internal_activityid() const {
  return _impl_.activityid_;
}
inline uint32_t MeshUnsubscribe::activityid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshUnsubscribe.activityId)
  return _internal_activityid();
}
inline void MeshUnsubscribe::_internal_set_activityid(uint32_t value) {
  
  _impl_.activityid_ = value;
}
inline void MeshUnsubscribe::set_activityid(uint32_t value) {
  _internal_set_activityid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshUnsubscribe.activityId)
}

// -------------------------------------------------------------------

// MeshPublish

// uint32 topicId = 1;
inline void MeshPublish::clear_topicid() {
  _impl_.topicid_ = 0u;
}
inline uint32_t MeshPublish::_internal_topicid() const {
  return _impl_.topicid_;
}
inline uint32_t MeshPublish::topicid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshPublish.topicId)
  return _internal_topicid();
}
inline void MeshPublish::_internal_set_topicid(uint32_t value) {
  
  _impl_.topicid_ = value;
}
inline void MeshPublish::set_topicid(uint32_t value) {
  _internal_set_topicid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshPublish.topicId)
}

// repeated bytes message = 3;
inline int MeshPublish::_internal_message_size() const {
  return _impl_.message_.size();
}
inline int MeshPublish::message_size() const {
  return _internal_message_size();
}
inline void MeshPublish::clear_message() {
  _impl_.message_.Clear();
}
inline std::string* MeshPublish::add_message() {
  std::string* _s = _internal_add_message();
  // @@protoc_insertion_point(field_add_mutable:herald.mesh.messages.MeshPublish.message)
  return _s;
}
inline const std::string& MeshPublish::_internal_message(int index) const {
  return _impl_.message_.Get(index);
}
inline const std::string& MeshPublish::message(int index) const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshPublish.message)
  return _internal_message(index);
}
inline std::string* MeshPublish::mutable_message(int index) {
  // @@protoc_insertion_point(field_mutable:herald.mesh.messages.MeshPublish.message)
  return _impl_.message_.Mutable(index);
}
inline void MeshPublish::set_message(int index, const std::string& value) {
  _impl_.message_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshPublish.message)
}
inline void MeshPublish::set_message(int index, std::string&& value) {
  _impl_.message_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshPublish.message)
}
inline void MeshPublish::set_message(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.message_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:herald.mesh.messages.MeshPublish.message)
}
inline void MeshPublish::set_message(int index, const void* value, size_t size) {
  _impl_.message_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:herald.mesh.messages.MeshPublish.message)
}
inline std::string* MeshPublish::_internal_add_message() {
  return _impl_.message_.Add();
}
inline void MeshPublish::add_message(const std::string& value) {
  _impl_.message_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:herald.mesh.messages.MeshPublish.message)
}
inline void MeshPublish::add_message(std::string&& value) {
  _impl_.message_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:herald.mesh.messages.MeshPublish.message)
}
inline void MeshPublish::add_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.message_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:herald.mesh.messages.MeshPublish.message)
}
inline void MeshPublish::add_message(const void* value, size_t size) {
  _impl_.message_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:herald.mesh.messages.MeshPublish.message)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MeshPublish::message() const {
  // @@protoc_insertion_point(field_list:herald.mesh.messages.MeshPublish.message)
  return _impl_.message_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MeshPublish::mutable_message() {
  // @@protoc_insertion_point(field_mutable_list:herald.mesh.messages.MeshPublish.message)
  return &_impl_.message_;
}

// -------------------------------------------------------------------

// MeshSend

// uint32 nodeId = 1;
inline void MeshSend::clear_nodeid() {
  _impl_.nodeid_ = 0u;
}
inline uint32_t MeshSend::_internal_nodeid() const {
  return _impl_.nodeid_;
}
inline uint32_t MeshSend::nodeid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSend.nodeId)
  return _internal_nodeid();
}
inline void MeshSend::_internal_set_nodeid(uint32_t value) {
  
  _impl_.nodeid_ = value;
}
inline void MeshSend::set_nodeid(uint32_t value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSend.nodeId)
}

// uint32 modelId = 2;
inline void MeshSend::clear_modelid() {
  _impl_.modelid_ = 0u;
}
inline uint32_t MeshSend::_internal_modelid() const {
  return _impl_.modelid_;
}
inline uint32_t MeshSend::modelid() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSend.modelId)
  return _internal_modelid();
}
inline void MeshSend::_internal_set_modelid(uint32_t value) {
  
  _impl_.modelid_ = value;
}
inline void MeshSend::set_modelid(uint32_t value) {
  _internal_set_modelid(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSend.modelId)
}

// repeated bytes message = 3;
inline int MeshSend::_internal_message_size() const {
  return _impl_.message_.size();
}
inline int MeshSend::message_size() const {
  return _internal_message_size();
}
inline void MeshSend::clear_message() {
  _impl_.message_.Clear();
}
inline std::string* MeshSend::add_message() {
  std::string* _s = _internal_add_message();
  // @@protoc_insertion_point(field_add_mutable:herald.mesh.messages.MeshSend.message)
  return _s;
}
inline const std::string& MeshSend::_internal_message(int index) const {
  return _impl_.message_.Get(index);
}
inline const std::string& MeshSend::message(int index) const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.MeshSend.message)
  return _internal_message(index);
}
inline std::string* MeshSend::mutable_message(int index) {
  // @@protoc_insertion_point(field_mutable:herald.mesh.messages.MeshSend.message)
  return _impl_.message_.Mutable(index);
}
inline void MeshSend::set_message(int index, const std::string& value) {
  _impl_.message_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSend.message)
}
inline void MeshSend::set_message(int index, std::string&& value) {
  _impl_.message_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:herald.mesh.messages.MeshSend.message)
}
inline void MeshSend::set_message(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.message_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:herald.mesh.messages.MeshSend.message)
}
inline void MeshSend::set_message(int index, const void* value, size_t size) {
  _impl_.message_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:herald.mesh.messages.MeshSend.message)
}
inline std::string* MeshSend::_internal_add_message() {
  return _impl_.message_.Add();
}
inline void MeshSend::add_message(const std::string& value) {
  _impl_.message_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:herald.mesh.messages.MeshSend.message)
}
inline void MeshSend::add_message(std::string&& value) {
  _impl_.message_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:herald.mesh.messages.MeshSend.message)
}
inline void MeshSend::add_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.message_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:herald.mesh.messages.MeshSend.message)
}
inline void MeshSend::add_message(const void* value, size_t size) {
  _impl_.message_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:herald.mesh.messages.MeshSend.message)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MeshSend::message() const {
  // @@protoc_insertion_point(field_list:herald.mesh.messages.MeshSend.message)
  return _impl_.message_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MeshSend::mutable_message() {
  // @@protoc_insertion_point(field_mutable_list:herald.mesh.messages.MeshSend.message)
  return &_impl_.message_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace mesh
}  // namespace herald

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_herald_2fmesh_2fmessages_2fmesh_2eproto
