// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: herald/mesh/messages/models.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_herald_2fmesh_2fmessages_2fmodels_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_herald_2fmesh_2fmessages_2fmodels_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_herald_2fmesh_2fmessages_2fmodels_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_herald_2fmesh_2fmessages_2fmodels_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto;
namespace herald {
namespace mesh {
namespace messages {
class Presence;
struct PresenceDefaultTypeInternal;
extern PresenceDefaultTypeInternal _Presence_default_instance_;
}  // namespace messages
}  // namespace mesh
}  // namespace herald
PROTOBUF_NAMESPACE_OPEN
template<> ::herald::mesh::messages::Presence* Arena::CreateMaybeMessage<::herald::mesh::messages::Presence>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace herald {
namespace mesh {
namespace messages {

enum Presence_Status : int {
  Presence_Status_OBSERVED = 0,
  Presence_Status_IDENTIFIED = 1,
  Presence_Status_VANISHED = 2,
  Presence_Status_Presence_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Presence_Status_Presence_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Presence_Status_IsValid(int value);
constexpr Presence_Status Presence_Status_Status_MIN = Presence_Status_OBSERVED;
constexpr Presence_Status Presence_Status_Status_MAX = Presence_Status_VANISHED;
constexpr int Presence_Status_Status_ARRAYSIZE = Presence_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Presence_Status_descriptor();
template<typename T>
inline const std::string& Presence_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Presence_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Presence_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Presence_Status_descriptor(), enum_t_value);
}
inline bool Presence_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Presence_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Presence_Status>(
    Presence_Status_descriptor(), name, value);
}
// ===================================================================

class Presence final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:herald.mesh.messages.Presence) */ {
 public:
  inline Presence() : Presence(nullptr) {}
  ~Presence() override;
  explicit PROTOBUF_CONSTEXPR Presence(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Presence(const Presence& from);
  Presence(Presence&& from) noexcept
    : Presence() {
    *this = ::std::move(from);
  }

  inline Presence& operator=(const Presence& from) {
    CopyFrom(from);
    return *this;
  }
  inline Presence& operator=(Presence&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Presence& default_instance() {
    return *internal_default_instance();
  }
  static inline const Presence* internal_default_instance() {
    return reinterpret_cast<const Presence*>(
               &_Presence_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Presence& a, Presence& b) {
    a.Swap(&b);
  }
  inline void Swap(Presence* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Presence* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Presence* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Presence>(arena);
  }
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Presence* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "herald.mesh.messages.Presence";
  }
  protected:
  explicit Presence(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Presence_Status Status;
  static constexpr Status OBSERVED =
    Presence_Status_OBSERVED;
  static constexpr Status IDENTIFIED =
    Presence_Status_IDENTIFIED;
  static constexpr Status VANISHED =
    Presence_Status_VANISHED;
  static inline bool Status_IsValid(int value) {
    return Presence_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    Presence_Status_Status_MIN;
  static constexpr Status Status_MAX =
    Presence_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    Presence_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return Presence_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return Presence_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return Presence_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMacFieldNumber = 1,
    kRssiFieldNumber = 2,
    kStatusFieldNumber = 3,
  };
  // uint64 mac = 1;
  void clear_mac();
  uint64_t mac() const;
  void set_mac(uint64_t value);
  private:
  uint64_t _internal_mac() const;
  void _internal_set_mac(uint64_t value);
  public:

  // int32 rssi = 2;
  void clear_rssi();
  int32_t rssi() const;
  void set_rssi(int32_t value);
  private:
  int32_t _internal_rssi() const;
  void _internal_set_rssi(int32_t value);
  public:

  // .herald.mesh.messages.Presence.Status status = 3;
  void clear_status();
  ::herald::mesh::messages::Presence_Status status() const;
  void set_status(::herald::mesh::messages::Presence_Status value);
  private:
  ::herald::mesh::messages::Presence_Status _internal_status() const;
  void _internal_set_status(::herald::mesh::messages::Presence_Status value);
  public:

  // @@protoc_insertion_point(class_scope:herald.mesh.messages.Presence)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t mac_;
    int32_t rssi_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_herald_2fmesh_2fmessages_2fmodels_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Presence

// uint64 mac = 1;
inline void Presence::clear_mac() {
  _impl_.mac_ = uint64_t{0u};
}
inline uint64_t Presence::_internal_mac() const {
  return _impl_.mac_;
}
inline uint64_t Presence::mac() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.Presence.mac)
  return _internal_mac();
}
inline void Presence::_internal_set_mac(uint64_t value) {
  
  _impl_.mac_ = value;
}
inline void Presence::set_mac(uint64_t value) {
  _internal_set_mac(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.Presence.mac)
}

// int32 rssi = 2;
inline void Presence::clear_rssi() {
  _impl_.rssi_ = 0;
}
inline int32_t Presence::_internal_rssi() const {
  return _impl_.rssi_;
}
inline int32_t Presence::rssi() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.Presence.rssi)
  return _internal_rssi();
}
inline void Presence::_internal_set_rssi(int32_t value) {
  
  _impl_.rssi_ = value;
}
inline void Presence::set_rssi(int32_t value) {
  _internal_set_rssi(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.Presence.rssi)
}

// .herald.mesh.messages.Presence.Status status = 3;
inline void Presence::clear_status() {
  _impl_.status_ = 0;
}
inline ::herald::mesh::messages::Presence_Status Presence::_internal_status() const {
  return static_cast< ::herald::mesh::messages::Presence_Status >(_impl_.status_);
}
inline ::herald::mesh::messages::Presence_Status Presence::status() const {
  // @@protoc_insertion_point(field_get:herald.mesh.messages.Presence.status)
  return _internal_status();
}
inline void Presence::_internal_set_status(::herald::mesh::messages::Presence_Status value) {
  
  _impl_.status_ = value;
}
inline void Presence::set_status(::herald::mesh::messages::Presence_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:herald.mesh.messages.Presence.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace mesh
}  // namespace herald

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::herald::mesh::messages::Presence_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::herald::mesh::messages::Presence_Status>() {
  return ::herald::mesh::messages::Presence_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_herald_2fmesh_2fmessages_2fmodels_2eproto
