# HERALD MINIMUM RUN REQUIREMENTS IN ZEPHYR FOR BL MESH

# Zephyr STD C++ API support - Required by the Herald API
CONFIG_CPLUSPLUS=y
# CONFIG_NEWLIB_LIBC=y
# CONFIG_LIB_CPLUSPLUS=y

# Bug in zephyr kernel includes - must enable USB if board forces it - see KConfig
# The below is no longer required in base as of NCS1.8/Zephyr2.7
#CONFIG_USB=y
# The below is what the symbol has changed to, but it's now in usb.conf
#CONFIG_USB_DEVICE_STACK=y

# Stops issues with disconnect MPU stack faults (Bug in zephyr/NCS?)
CONFIG_ARM_MPU=n