// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: herald/mesh/messages/mesh.proto

#include "herald/mesh/messages/mesh.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace herald {
namespace mesh {
namespace messages {
PROTOBUF_CONSTEXPR MeshGet::MeshGet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_.modelid_)*/0u
  , /*decltype(_impl_.fieldid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshGetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshGetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshGetDefaultTypeInternal() {}
  union {
    MeshGet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshGetDefaultTypeInternal _MeshGet_default_instance_;
PROTOBUF_CONSTEXPR MeshSet::MeshSet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_.modelid_)*/0u
  , /*decltype(_impl_.fieldid_)*/0u
  , /*decltype(_impl_.reply_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshSetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshSetDefaultTypeInternal() {}
  union {
    MeshSet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshSetDefaultTypeInternal _MeshSet_default_instance_;
PROTOBUF_CONSTEXPR MeshSubscribe::MeshSubscribe(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_.modelid_)*/0u
  , /*decltype(_impl_.activityid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshSubscribeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshSubscribeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshSubscribeDefaultTypeInternal() {}
  union {
    MeshSubscribe _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshSubscribeDefaultTypeInternal _MeshSubscribe_default_instance_;
PROTOBUF_CONSTEXPR MeshUnsubscribe::MeshUnsubscribe(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_.modelid_)*/0u
  , /*decltype(_impl_.activityid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshUnsubscribeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshUnsubscribeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshUnsubscribeDefaultTypeInternal() {}
  union {
    MeshUnsubscribe _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshUnsubscribeDefaultTypeInternal _MeshUnsubscribe_default_instance_;
PROTOBUF_CONSTEXPR MeshPublish::MeshPublish(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{}
  , /*decltype(_impl_.topicid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshPublishDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshPublishDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshPublishDefaultTypeInternal() {}
  union {
    MeshPublish _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshPublishDefaultTypeInternal _MeshPublish_default_instance_;
PROTOBUF_CONSTEXPR MeshSend::MeshSend(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{}
  , /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_.modelid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshSendDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshSendDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshSendDefaultTypeInternal() {}
  union {
    MeshSend _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshSendDefaultTypeInternal _MeshSend_default_instance_;
}  // namespace messages
}  // namespace mesh
}  // namespace herald
static ::_pb::Metadata file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmesh_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_herald_2fmesh_2fmessages_2fmesh_2eproto = nullptr;

const uint32_t TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGet, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGet, _impl_.modelid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGet, _impl_.fieldid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSet, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSet, _impl_.modelid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSet, _impl_.fieldid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSet, _impl_.reply_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribe, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribe, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribe, _impl_.modelid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribe, _impl_.activityid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribe, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribe, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribe, _impl_.modelid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribe, _impl_.activityid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshPublish, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshPublish, _impl_.topicid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshPublish, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSend, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSend, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSend, _impl_.modelid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSend, _impl_.message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::herald::mesh::messages::MeshGet)},
  { 9, -1, -1, sizeof(::herald::mesh::messages::MeshSet)},
  { 19, -1, -1, sizeof(::herald::mesh::messages::MeshSubscribe)},
  { 28, -1, -1, sizeof(::herald::mesh::messages::MeshUnsubscribe)},
  { 37, -1, -1, sizeof(::herald::mesh::messages::MeshPublish)},
  { 45, -1, -1, sizeof(::herald::mesh::messages::MeshSend)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::herald::mesh::messages::_MeshGet_default_instance_._instance,
  &::herald::mesh::messages::_MeshSet_default_instance_._instance,
  &::herald::mesh::messages::_MeshSubscribe_default_instance_._instance,
  &::herald::mesh::messages::_MeshUnsubscribe_default_instance_._instance,
  &::herald::mesh::messages::_MeshPublish_default_instance_._instance,
  &::herald::mesh::messages::_MeshSend_default_instance_._instance,
};

const char descriptor_table_protodef_herald_2fmesh_2fmessages_2fmesh_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037herald/mesh/messages/mesh.proto\022\024heral"
  "d.mesh.messages\";\n\007MeshGet\022\016\n\006nodeId\030\001 \001"
  "(\r\022\017\n\007modelId\030\002 \001(\r\022\017\n\007fieldId\030\003 \001(\r\"J\n\007"
  "MeshSet\022\016\n\006nodeId\030\001 \001(\r\022\017\n\007modelId\030\002 \001(\r"
  "\022\017\n\007fieldId\030\003 \001(\r\022\r\n\005reply\030\004 \001(\010\"D\n\rMesh"
  "Subscribe\022\016\n\006nodeId\030\001 \001(\r\022\017\n\007modelId\030\002 \001"
  "(\r\022\022\n\nactivityId\030\003 \001(\r\"F\n\017MeshUnsubscrib"
  "e\022\016\n\006nodeId\030\001 \001(\r\022\017\n\007modelId\030\002 \001(\r\022\022\n\nac"
  "tivityId\030\003 \001(\r\"/\n\013MeshPublish\022\017\n\007topicId"
  "\030\001 \001(\r\022\017\n\007message\030\003 \003(\014\"<\n\010MeshSend\022\016\n\006n"
  "odeId\030\001 \001(\r\022\017\n\007modelId\030\002 \001(\r\022\017\n\007message\030"
  "\003 \003(\014B\002H\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto = {
    false, false, 457, descriptor_table_protodef_herald_2fmesh_2fmessages_2fmesh_2eproto,
    "herald/mesh/messages/mesh.proto",
    &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_herald_2fmesh_2fmessages_2fmesh_2eproto::offsets,
    file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto, file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmesh_2eproto,
    file_level_service_descriptors_herald_2fmesh_2fmessages_2fmesh_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter() {
  return &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_herald_2fmesh_2fmessages_2fmesh_2eproto(&descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto);
namespace herald {
namespace mesh {
namespace messages {

// ===================================================================

class MeshGet::_Internal {
 public:
};

MeshGet::MeshGet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshGet)
}
MeshGet::MeshGet(const MeshGet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshGet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){}
    , decltype(_impl_.modelid_){}
    , decltype(_impl_.fieldid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.nodeid_, &from._impl_.nodeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.fieldid_) -
    reinterpret_cast<char*>(&_impl_.nodeid_)) + sizeof(_impl_.fieldid_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshGet)
}

inline void MeshGet::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){0u}
    , decltype(_impl_.modelid_){0u}
    , decltype(_impl_.fieldid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshGet::~MeshGet() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshGet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshGet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MeshGet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshGet::InternalSwap(MeshGet* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshGet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[0]);
}

// ===================================================================

class MeshSet::_Internal {
 public:
};

MeshSet::MeshSet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshSet)
}
MeshSet::MeshSet(const MeshSet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshSet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){}
    , decltype(_impl_.modelid_){}
    , decltype(_impl_.fieldid_){}
    , decltype(_impl_.reply_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.nodeid_, &from._impl_.nodeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.reply_) -
    reinterpret_cast<char*>(&_impl_.nodeid_)) + sizeof(_impl_.reply_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshSet)
}

inline void MeshSet::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){0u}
    , decltype(_impl_.modelid_){0u}
    , decltype(_impl_.fieldid_){0u}
    , decltype(_impl_.reply_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshSet::~MeshSet() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshSet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshSet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MeshSet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshSet::InternalSwap(MeshSet* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshSet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[1]);
}

// ===================================================================

class MeshSubscribe::_Internal {
 public:
};

MeshSubscribe::MeshSubscribe(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshSubscribe)
}
MeshSubscribe::MeshSubscribe(const MeshSubscribe& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshSubscribe* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){}
    , decltype(_impl_.modelid_){}
    , decltype(_impl_.activityid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.nodeid_, &from._impl_.nodeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.activityid_) -
    reinterpret_cast<char*>(&_impl_.nodeid_)) + sizeof(_impl_.activityid_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshSubscribe)
}

inline void MeshSubscribe::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){0u}
    , decltype(_impl_.modelid_){0u}
    , decltype(_impl_.activityid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshSubscribe::~MeshSubscribe() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshSubscribe)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshSubscribe::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MeshSubscribe::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshSubscribe::InternalSwap(MeshSubscribe* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshSubscribe::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[2]);
}

// ===================================================================

class MeshUnsubscribe::_Internal {
 public:
};

MeshUnsubscribe::MeshUnsubscribe(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshUnsubscribe)
}
MeshUnsubscribe::MeshUnsubscribe(const MeshUnsubscribe& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshUnsubscribe* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){}
    , decltype(_impl_.modelid_){}
    , decltype(_impl_.activityid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.nodeid_, &from._impl_.nodeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.activityid_) -
    reinterpret_cast<char*>(&_impl_.nodeid_)) + sizeof(_impl_.activityid_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshUnsubscribe)
}

inline void MeshUnsubscribe::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){0u}
    , decltype(_impl_.modelid_){0u}
    , decltype(_impl_.activityid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshUnsubscribe::~MeshUnsubscribe() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshUnsubscribe)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshUnsubscribe::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MeshUnsubscribe::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshUnsubscribe::InternalSwap(MeshUnsubscribe* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshUnsubscribe::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[3]);
}

// ===================================================================

class MeshPublish::_Internal {
 public:
};

MeshPublish::MeshPublish(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshPublish)
}
MeshPublish::MeshPublish(const MeshPublish& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshPublish* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){from._impl_.message_}
    , decltype(_impl_.topicid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.topicid_ = from._impl_.topicid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshPublish)
}

inline void MeshPublish::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){arena}
    , decltype(_impl_.topicid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshPublish::~MeshPublish() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshPublish)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshPublish::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.~RepeatedPtrField();
}

void MeshPublish::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshPublish::InternalSwap(MeshPublish* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshPublish::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[4]);
}

// ===================================================================

class MeshSend::_Internal {
 public:
};

MeshSend::MeshSend(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshSend)
}
MeshSend::MeshSend(const MeshSend& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshSend* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){from._impl_.message_}
    , decltype(_impl_.nodeid_){}
    , decltype(_impl_.modelid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.nodeid_, &from._impl_.nodeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.modelid_) -
    reinterpret_cast<char*>(&_impl_.nodeid_)) + sizeof(_impl_.modelid_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshSend)
}

inline void MeshSend::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){arena}
    , decltype(_impl_.nodeid_){0u}
    , decltype(_impl_.modelid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshSend::~MeshSend() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshSend)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshSend::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.~RepeatedPtrField();
}

void MeshSend::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshSend::InternalSwap(MeshSend* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshSend::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmesh_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace mesh
}  // namespace herald
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshGet*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshGet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshGet >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshSet*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshSet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshSet >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshSubscribe*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshSubscribe >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshSubscribe >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshUnsubscribe*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshUnsubscribe >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshUnsubscribe >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshPublish*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshPublish >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshPublish >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshSend*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshSend >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshSend >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
