// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: herald/mesh/messages/modem.proto

#include "herald/mesh/messages/modem.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace herald {
namespace mesh {
namespace messages {
PROTOBUF_CONSTEXPR Hello::Hello(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HelloDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HelloDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HelloDefaultTypeInternal() {}
  union {
    Hello _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HelloDefaultTypeInternal _Hello_default_instance_;
PROTOBUF_CONSTEXPR Ok::Ok(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OkDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OkDefaultTypeInternal() {}
  union {
    Ok _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OkDefaultTypeInternal _Ok_default_instance_;
PROTOBUF_CONSTEXPR Invalid::Invalid(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.explanation_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}} {}
struct InvalidDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvalidDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvalidDefaultTypeInternal() {}
  union {
    Invalid _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvalidDefaultTypeInternal _Invalid_default_instance_;
PROTOBUF_CONSTEXPR TimedOut::TimedOut(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TimedOutDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TimedOutDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TimedOutDefaultTypeInternal() {}
  union {
    TimedOut _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TimedOutDefaultTypeInternal _TimedOut_default_instance_;
PROTOBUF_CONSTEXPR SetNetworkKey::SetNetworkKey(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_.key_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetNetworkKeyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetNetworkKeyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetNetworkKeyDefaultTypeInternal() {}
  union {
    SetNetworkKey _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetNetworkKeyDefaultTypeInternal _SetNetworkKey_default_instance_;
PROTOBUF_CONSTEXPR MeshGetCommand::MeshGetCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.get_)*/nullptr
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshGetCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshGetCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshGetCommandDefaultTypeInternal() {}
  union {
    MeshGetCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshGetCommandDefaultTypeInternal _MeshGetCommand_default_instance_;
PROTOBUF_CONSTEXPR MeshSetCommand::MeshSetCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.set_)*/nullptr
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshSetCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshSetCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshSetCommandDefaultTypeInternal() {}
  union {
    MeshSetCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshSetCommandDefaultTypeInternal _MeshSetCommand_default_instance_;
PROTOBUF_CONSTEXPR MeshSubscribeCommand::MeshSubscribeCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.subscribe_)*/nullptr
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshSubscribeCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshSubscribeCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshSubscribeCommandDefaultTypeInternal() {}
  union {
    MeshSubscribeCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshSubscribeCommandDefaultTypeInternal _MeshSubscribeCommand_default_instance_;
PROTOBUF_CONSTEXPR MeshUnsubscribeCommand::MeshUnsubscribeCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.unsubscribe_)*/nullptr
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshUnsubscribeCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshUnsubscribeCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshUnsubscribeCommandDefaultTypeInternal() {}
  union {
    MeshUnsubscribeCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshUnsubscribeCommandDefaultTypeInternal _MeshUnsubscribeCommand_default_instance_;
PROTOBUF_CONSTEXPR MeshPublishCommand::MeshPublishCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.publish_)*/nullptr
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshPublishCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshPublishCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshPublishCommandDefaultTypeInternal() {}
  union {
    MeshPublishCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshPublishCommandDefaultTypeInternal _MeshPublishCommand_default_instance_;
PROTOBUF_CONSTEXPR MeshSendCommand::MeshSendCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.send_)*/nullptr
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshSendCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshSendCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshSendCommandDefaultTypeInternal() {}
  union {
    MeshSendCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshSendCommandDefaultTypeInternal _MeshSendCommand_default_instance_;
PROTOBUF_CONSTEXPR GetKnownMeshNodes::GetKnownMeshNodes(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_.fromnodeid_)*/0u} {}
struct GetKnownMeshNodesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetKnownMeshNodesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetKnownMeshNodesDefaultTypeInternal() {}
  union {
    GetKnownMeshNodes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetKnownMeshNodesDefaultTypeInternal _GetKnownMeshNodes_default_instance_;
PROTOBUF_CONSTEXPR MeshNodeSummary::MeshNodeSummary(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MeshNodeSummaryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MeshNodeSummaryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MeshNodeSummaryDefaultTypeInternal() {}
  union {
    MeshNodeSummary _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MeshNodeSummaryDefaultTypeInternal _MeshNodeSummary_default_instance_;
PROTOBUF_CONSTEXPR KnownMeshNodes::KnownMeshNodes(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.known_)*/{}
  , /*decltype(_impl_.commandid_)*/uint64_t{0u}
  , /*decltype(_impl_.nodeid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KnownMeshNodesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KnownMeshNodesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KnownMeshNodesDefaultTypeInternal() {}
  union {
    KnownMeshNodes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KnownMeshNodesDefaultTypeInternal _KnownMeshNodes_default_instance_;
}  // namespace messages
}  // namespace mesh
}  // namespace herald
static ::_pb::Metadata file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[14];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmodem_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_herald_2fmesh_2fmessages_2fmodem_2eproto = nullptr;

const uint32_t TableStruct_herald_2fmesh_2fmessages_2fmodem_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Hello, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Hello, _impl_.commandid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Ok, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Ok, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Invalid, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Invalid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Invalid, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Invalid, _impl_.explanation_),
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::TimedOut, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::TimedOut, _impl_.commandid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::SetNetworkKey, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::SetNetworkKey, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::SetNetworkKey, _impl_.key_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGetCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGetCommand, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshGetCommand, _impl_.get_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSetCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSetCommand, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSetCommand, _impl_.set_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribeCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribeCommand, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSubscribeCommand, _impl_.subscribe_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribeCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribeCommand, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshUnsubscribeCommand, _impl_.unsubscribe_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshPublishCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshPublishCommand, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshPublishCommand, _impl_.publish_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSendCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSendCommand, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshSendCommand, _impl_.send_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::GetKnownMeshNodes, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::GetKnownMeshNodes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::GetKnownMeshNodes, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::GetKnownMeshNodes, _impl_.fromnodeid_),
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshNodeSummary, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::MeshNodeSummary, _impl_.nodeid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::KnownMeshNodes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::KnownMeshNodes, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::KnownMeshNodes, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::KnownMeshNodes, _impl_.known_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::herald::mesh::messages::Hello)},
  { 7, -1, -1, sizeof(::herald::mesh::messages::Ok)},
  { 14, 22, -1, sizeof(::herald::mesh::messages::Invalid)},
  { 24, -1, -1, sizeof(::herald::mesh::messages::TimedOut)},
  { 31, -1, -1, sizeof(::herald::mesh::messages::SetNetworkKey)},
  { 39, -1, -1, sizeof(::herald::mesh::messages::MeshGetCommand)},
  { 47, -1, -1, sizeof(::herald::mesh::messages::MeshSetCommand)},
  { 55, -1, -1, sizeof(::herald::mesh::messages::MeshSubscribeCommand)},
  { 63, -1, -1, sizeof(::herald::mesh::messages::MeshUnsubscribeCommand)},
  { 71, -1, -1, sizeof(::herald::mesh::messages::MeshPublishCommand)},
  { 79, -1, -1, sizeof(::herald::mesh::messages::MeshSendCommand)},
  { 87, 95, -1, sizeof(::herald::mesh::messages::GetKnownMeshNodes)},
  { 97, -1, -1, sizeof(::herald::mesh::messages::MeshNodeSummary)},
  { 104, -1, -1, sizeof(::herald::mesh::messages::KnownMeshNodes)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::herald::mesh::messages::_Hello_default_instance_._instance,
  &::herald::mesh::messages::_Ok_default_instance_._instance,
  &::herald::mesh::messages::_Invalid_default_instance_._instance,
  &::herald::mesh::messages::_TimedOut_default_instance_._instance,
  &::herald::mesh::messages::_SetNetworkKey_default_instance_._instance,
  &::herald::mesh::messages::_MeshGetCommand_default_instance_._instance,
  &::herald::mesh::messages::_MeshSetCommand_default_instance_._instance,
  &::herald::mesh::messages::_MeshSubscribeCommand_default_instance_._instance,
  &::herald::mesh::messages::_MeshUnsubscribeCommand_default_instance_._instance,
  &::herald::mesh::messages::_MeshPublishCommand_default_instance_._instance,
  &::herald::mesh::messages::_MeshSendCommand_default_instance_._instance,
  &::herald::mesh::messages::_GetKnownMeshNodes_default_instance_._instance,
  &::herald::mesh::messages::_MeshNodeSummary_default_instance_._instance,
  &::herald::mesh::messages::_KnownMeshNodes_default_instance_._instance,
};

const char descriptor_table_protodef_herald_2fmesh_2fmessages_2fmodem_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n herald/mesh/messages/modem.proto\022\024hera"
  "ld.mesh.messages\032\037herald/mesh/messages/m"
  "esh.proto\032!herald/mesh/messages/models.p"
  "roto\"\032\n\005Hello\022\021\n\tcommandId\030\001 \001(\004\"\027\n\002Ok\022\021"
  "\n\tcommandId\030\001 \001(\004\"F\n\007Invalid\022\021\n\tcommandI"
  "d\030\001 \001(\004\022\030\n\013explanation\030\002 \001(\tH\000\210\001\001B\016\n\014_ex"
  "planation\"\035\n\010TimedOut\022\021\n\tcommandId\030\001 \001(\004"
  "\"/\n\rSetNetworkKey\022\021\n\tcommandId\030\001 \001(\004\022\013\n\003"
  "key\030\002 \001(\004\"O\n\016MeshGetCommand\022\021\n\tcommandId"
  "\030\001 \001(\004\022*\n\003get\030\002 \001(\0132\035.herald.mesh.messag"
  "es.MeshGet\"O\n\016MeshSetCommand\022\021\n\tcommandI"
  "d\030\001 \001(\004\022*\n\003set\030\002 \001(\0132\035.herald.mesh.messa"
  "ges.MeshSet\"a\n\024MeshSubscribeCommand\022\021\n\tc"
  "ommandId\030\001 \001(\004\0226\n\tsubscribe\030\002 \001(\0132#.hera"
  "ld.mesh.messages.MeshSubscribe\"g\n\026MeshUn"
  "subscribeCommand\022\021\n\tcommandId\030\001 \001(\004\022:\n\013u"
  "nsubscribe\030\002 \001(\0132%.herald.mesh.messages."
  "MeshUnsubscribe\"[\n\022MeshPublishCommand\022\021\n"
  "\tcommandId\030\001 \001(\004\0222\n\007publish\030\002 \001(\0132!.hera"
  "ld.mesh.messages.MeshPublish\"R\n\017MeshSend"
  "Command\022\021\n\tcommandId\030\001 \001(\004\022,\n\004send\030\002 \001(\013"
  "2\036.herald.mesh.messages.MeshSend\"N\n\021GetK"
  "nownMeshNodes\022\021\n\tcommandId\030\001 \001(\004\022\027\n\nfrom"
  "NodeId\030\002 \001(\rH\000\210\001\001B\r\n\013_fromNodeId\"!\n\017Mesh"
  "NodeSummary\022\016\n\006nodeId\030\002 \001(\r\"i\n\016KnownMesh"
  "Nodes\022\021\n\tcommandId\030\001 \001(\004\022\016\n\006nodeId\030\002 \001(\r"
  "\0224\n\005known\030\003 \003(\0132%.herald.mesh.messages.M"
  "eshNodeSummaryB\002H\002b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_deps[2] = {
  &::descriptor_table_herald_2fmesh_2fmessages_2fmesh_2eproto,
  &::descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto,
};
static ::_pbi::once_flag descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto = {
    false, false, 1106, descriptor_table_protodef_herald_2fmesh_2fmessages_2fmodem_2eproto,
    "herald/mesh/messages/modem.proto",
    &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once, descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_deps, 2, 14,
    schemas, file_default_instances, TableStruct_herald_2fmesh_2fmessages_2fmodem_2eproto::offsets,
    file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto, file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmodem_2eproto,
    file_level_service_descriptors_herald_2fmesh_2fmessages_2fmodem_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter() {
  return &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_herald_2fmesh_2fmessages_2fmodem_2eproto(&descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto);
namespace herald {
namespace mesh {
namespace messages {

// ===================================================================

class Hello::_Internal {
 public:
};

Hello::Hello(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.Hello)
}
Hello::Hello(const Hello& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Hello* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.Hello)
}

inline void Hello::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Hello::~Hello() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.Hello)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Hello::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Hello::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Hello::InternalSwap(Hello* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Hello::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[0]);
}

// ===================================================================

class Ok::_Internal {
 public:
};

Ok::Ok(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.Ok)
}
Ok::Ok(const Ok& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Ok* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.Ok)
}

inline void Ok::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Ok::~Ok() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.Ok)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Ok::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Ok::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Ok::InternalSwap(Ok* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Ok::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[1]);
}

// ===================================================================

class Invalid::_Internal {
 public:
  using HasBits = decltype(std::declval<Invalid>()._impl_._has_bits_);
  static void set_has_explanation(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Invalid::Invalid(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.Invalid)
}
Invalid::Invalid(const Invalid& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Invalid* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.explanation_){}
    , decltype(_impl_.commandid_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.explanation_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.explanation_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_explanation()) {
    _this->_impl_.explanation_.Set(from._internal_explanation(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.Invalid)
}

inline void Invalid::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.explanation_){}
    , decltype(_impl_.commandid_){uint64_t{0u}}
  };
  _impl_.explanation_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.explanation_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Invalid::~Invalid() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.Invalid)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Invalid::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.explanation_.Destroy();
}

void Invalid::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Invalid::InternalSwap(Invalid* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Invalid::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[2]);
}

// ===================================================================

class TimedOut::_Internal {
 public:
};

TimedOut::TimedOut(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.TimedOut)
}
TimedOut::TimedOut(const TimedOut& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TimedOut* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.TimedOut)
}

inline void TimedOut::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TimedOut::~TimedOut() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.TimedOut)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TimedOut::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TimedOut::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TimedOut::InternalSwap(TimedOut* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata TimedOut::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[3]);
}

// ===================================================================

class SetNetworkKey::_Internal {
 public:
};

SetNetworkKey::SetNetworkKey(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.SetNetworkKey)
}
SetNetworkKey::SetNetworkKey(const SetNetworkKey& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetNetworkKey* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){}
    , decltype(_impl_.key_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.commandid_, &from._impl_.commandid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.key_) -
    reinterpret_cast<char*>(&_impl_.commandid_)) + sizeof(_impl_.key_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.SetNetworkKey)
}

inline void SetNetworkKey::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.commandid_){uint64_t{0u}}
    , decltype(_impl_.key_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SetNetworkKey::~SetNetworkKey() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.SetNetworkKey)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SetNetworkKey::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SetNetworkKey::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetNetworkKey::InternalSwap(SetNetworkKey* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata SetNetworkKey::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[4]);
}

// ===================================================================

class MeshGetCommand::_Internal {
 public:
  static const ::herald::mesh::messages::MeshGet& get(const MeshGetCommand* msg);
};

const ::herald::mesh::messages::MeshGet&
MeshGetCommand::_Internal::get(const MeshGetCommand* msg) {
  return *msg->_impl_.get_;
}
void MeshGetCommand::clear_get() {
  if (GetArenaForAllocation() == nullptr && _impl_.get_ != nullptr) {
    delete _impl_.get_;
  }
  _impl_.get_ = nullptr;
}
MeshGetCommand::MeshGetCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshGetCommand)
}
MeshGetCommand::MeshGetCommand(const MeshGetCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshGetCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.get_){nullptr}
    , decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_get()) {
    _this->_impl_.get_ = new ::herald::mesh::messages::MeshGet(*from._impl_.get_);
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshGetCommand)
}

inline void MeshGetCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.get_){nullptr}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshGetCommand::~MeshGetCommand() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshGetCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshGetCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.get_;
}

void MeshGetCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshGetCommand::InternalSwap(MeshGetCommand* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshGetCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[5]);
}

// ===================================================================

class MeshSetCommand::_Internal {
 public:
  static const ::herald::mesh::messages::MeshSet& set(const MeshSetCommand* msg);
};

const ::herald::mesh::messages::MeshSet&
MeshSetCommand::_Internal::set(const MeshSetCommand* msg) {
  return *msg->_impl_.set_;
}
void MeshSetCommand::clear_set() {
  if (GetArenaForAllocation() == nullptr && _impl_.set_ != nullptr) {
    delete _impl_.set_;
  }
  _impl_.set_ = nullptr;
}
MeshSetCommand::MeshSetCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshSetCommand)
}
MeshSetCommand::MeshSetCommand(const MeshSetCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshSetCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.set_){nullptr}
    , decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_set()) {
    _this->_impl_.set_ = new ::herald::mesh::messages::MeshSet(*from._impl_.set_);
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshSetCommand)
}

inline void MeshSetCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.set_){nullptr}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshSetCommand::~MeshSetCommand() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshSetCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshSetCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.set_;
}

void MeshSetCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshSetCommand::InternalSwap(MeshSetCommand* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshSetCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[6]);
}

// ===================================================================

class MeshSubscribeCommand::_Internal {
 public:
  static const ::herald::mesh::messages::MeshSubscribe& subscribe(const MeshSubscribeCommand* msg);
};

const ::herald::mesh::messages::MeshSubscribe&
MeshSubscribeCommand::_Internal::subscribe(const MeshSubscribeCommand* msg) {
  return *msg->_impl_.subscribe_;
}
void MeshSubscribeCommand::clear_subscribe() {
  if (GetArenaForAllocation() == nullptr && _impl_.subscribe_ != nullptr) {
    delete _impl_.subscribe_;
  }
  _impl_.subscribe_ = nullptr;
}
MeshSubscribeCommand::MeshSubscribeCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshSubscribeCommand)
}
MeshSubscribeCommand::MeshSubscribeCommand(const MeshSubscribeCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshSubscribeCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.subscribe_){nullptr}
    , decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_subscribe()) {
    _this->_impl_.subscribe_ = new ::herald::mesh::messages::MeshSubscribe(*from._impl_.subscribe_);
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshSubscribeCommand)
}

inline void MeshSubscribeCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.subscribe_){nullptr}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshSubscribeCommand::~MeshSubscribeCommand() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshSubscribeCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshSubscribeCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.subscribe_;
}

void MeshSubscribeCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshSubscribeCommand::InternalSwap(MeshSubscribeCommand* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshSubscribeCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[7]);
}

// ===================================================================

class MeshUnsubscribeCommand::_Internal {
 public:
  static const ::herald::mesh::messages::MeshUnsubscribe& unsubscribe(const MeshUnsubscribeCommand* msg);
};

const ::herald::mesh::messages::MeshUnsubscribe&
MeshUnsubscribeCommand::_Internal::unsubscribe(const MeshUnsubscribeCommand* msg) {
  return *msg->_impl_.unsubscribe_;
}
void MeshUnsubscribeCommand::clear_unsubscribe() {
  if (GetArenaForAllocation() == nullptr && _impl_.unsubscribe_ != nullptr) {
    delete _impl_.unsubscribe_;
  }
  _impl_.unsubscribe_ = nullptr;
}
MeshUnsubscribeCommand::MeshUnsubscribeCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshUnsubscribeCommand)
}
MeshUnsubscribeCommand::MeshUnsubscribeCommand(const MeshUnsubscribeCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshUnsubscribeCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.unsubscribe_){nullptr}
    , decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_unsubscribe()) {
    _this->_impl_.unsubscribe_ = new ::herald::mesh::messages::MeshUnsubscribe(*from._impl_.unsubscribe_);
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshUnsubscribeCommand)
}

inline void MeshUnsubscribeCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.unsubscribe_){nullptr}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshUnsubscribeCommand::~MeshUnsubscribeCommand() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshUnsubscribeCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshUnsubscribeCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.unsubscribe_;
}

void MeshUnsubscribeCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshUnsubscribeCommand::InternalSwap(MeshUnsubscribeCommand* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshUnsubscribeCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[8]);
}

// ===================================================================

class MeshPublishCommand::_Internal {
 public:
  static const ::herald::mesh::messages::MeshPublish& publish(const MeshPublishCommand* msg);
};

const ::herald::mesh::messages::MeshPublish&
MeshPublishCommand::_Internal::publish(const MeshPublishCommand* msg) {
  return *msg->_impl_.publish_;
}
void MeshPublishCommand::clear_publish() {
  if (GetArenaForAllocation() == nullptr && _impl_.publish_ != nullptr) {
    delete _impl_.publish_;
  }
  _impl_.publish_ = nullptr;
}
MeshPublishCommand::MeshPublishCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshPublishCommand)
}
MeshPublishCommand::MeshPublishCommand(const MeshPublishCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshPublishCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.publish_){nullptr}
    , decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_publish()) {
    _this->_impl_.publish_ = new ::herald::mesh::messages::MeshPublish(*from._impl_.publish_);
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshPublishCommand)
}

inline void MeshPublishCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.publish_){nullptr}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshPublishCommand::~MeshPublishCommand() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshPublishCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshPublishCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.publish_;
}

void MeshPublishCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshPublishCommand::InternalSwap(MeshPublishCommand* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshPublishCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[9]);
}

// ===================================================================

class MeshSendCommand::_Internal {
 public:
  static const ::herald::mesh::messages::MeshSend& send(const MeshSendCommand* msg);
};

const ::herald::mesh::messages::MeshSend&
MeshSendCommand::_Internal::send(const MeshSendCommand* msg) {
  return *msg->_impl_.send_;
}
void MeshSendCommand::clear_send() {
  if (GetArenaForAllocation() == nullptr && _impl_.send_ != nullptr) {
    delete _impl_.send_;
  }
  _impl_.send_ = nullptr;
}
MeshSendCommand::MeshSendCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshSendCommand)
}
MeshSendCommand::MeshSendCommand(const MeshSendCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshSendCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.send_){nullptr}
    , decltype(_impl_.commandid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_send()) {
    _this->_impl_.send_ = new ::herald::mesh::messages::MeshSend(*from._impl_.send_);
  }
  _this->_impl_.commandid_ = from._impl_.commandid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshSendCommand)
}

inline void MeshSendCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.send_){nullptr}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshSendCommand::~MeshSendCommand() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshSendCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshSendCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.send_;
}

void MeshSendCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshSendCommand::InternalSwap(MeshSendCommand* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshSendCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[10]);
}

// ===================================================================

class GetKnownMeshNodes::_Internal {
 public:
  using HasBits = decltype(std::declval<GetKnownMeshNodes>()._impl_._has_bits_);
  static void set_has_fromnodeid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

GetKnownMeshNodes::GetKnownMeshNodes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.GetKnownMeshNodes)
}
GetKnownMeshNodes::GetKnownMeshNodes(const GetKnownMeshNodes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetKnownMeshNodes* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.commandid_){}
    , decltype(_impl_.fromnodeid_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.commandid_, &from._impl_.commandid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.fromnodeid_) -
    reinterpret_cast<char*>(&_impl_.commandid_)) + sizeof(_impl_.fromnodeid_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.GetKnownMeshNodes)
}

inline void GetKnownMeshNodes::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , decltype(_impl_.fromnodeid_){0u}
  };
}

GetKnownMeshNodes::~GetKnownMeshNodes() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.GetKnownMeshNodes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetKnownMeshNodes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetKnownMeshNodes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetKnownMeshNodes::InternalSwap(GetKnownMeshNodes* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata GetKnownMeshNodes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[11]);
}

// ===================================================================

class MeshNodeSummary::_Internal {
 public:
};

MeshNodeSummary::MeshNodeSummary(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.MeshNodeSummary)
}
MeshNodeSummary::MeshNodeSummary(const MeshNodeSummary& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MeshNodeSummary* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.nodeid_ = from._impl_.nodeid_;
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.MeshNodeSummary)
}

inline void MeshNodeSummary::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nodeid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MeshNodeSummary::~MeshNodeSummary() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.MeshNodeSummary)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MeshNodeSummary::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MeshNodeSummary::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MeshNodeSummary::InternalSwap(MeshNodeSummary* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata MeshNodeSummary::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[12]);
}

// ===================================================================

class KnownMeshNodes::_Internal {
 public:
};

KnownMeshNodes::KnownMeshNodes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.KnownMeshNodes)
}
KnownMeshNodes::KnownMeshNodes(const KnownMeshNodes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KnownMeshNodes* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.known_){from._impl_.known_}
    , decltype(_impl_.commandid_){}
    , decltype(_impl_.nodeid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.commandid_, &from._impl_.commandid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.nodeid_) -
    reinterpret_cast<char*>(&_impl_.commandid_)) + sizeof(_impl_.nodeid_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.KnownMeshNodes)
}

inline void KnownMeshNodes::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.known_){arena}
    , decltype(_impl_.commandid_){uint64_t{0u}}
    , decltype(_impl_.nodeid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

KnownMeshNodes::~KnownMeshNodes() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.KnownMeshNodes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KnownMeshNodes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.known_.~RepeatedPtrField();
}

void KnownMeshNodes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KnownMeshNodes::InternalSwap(KnownMeshNodes* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata KnownMeshNodes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodem_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodem_2eproto[13]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace mesh
}  // namespace herald
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::Hello*
Arena::CreateMaybeMessage< ::herald::mesh::messages::Hello >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::Hello >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::Ok*
Arena::CreateMaybeMessage< ::herald::mesh::messages::Ok >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::Ok >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::Invalid*
Arena::CreateMaybeMessage< ::herald::mesh::messages::Invalid >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::Invalid >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::TimedOut*
Arena::CreateMaybeMessage< ::herald::mesh::messages::TimedOut >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::TimedOut >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::SetNetworkKey*
Arena::CreateMaybeMessage< ::herald::mesh::messages::SetNetworkKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::SetNetworkKey >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshGetCommand*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshGetCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshGetCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshSetCommand*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshSetCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshSetCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshSubscribeCommand*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshSubscribeCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshSubscribeCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshUnsubscribeCommand*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshUnsubscribeCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshUnsubscribeCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshPublishCommand*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshPublishCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshPublishCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshSendCommand*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshSendCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshSendCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::GetKnownMeshNodes*
Arena::CreateMaybeMessage< ::herald::mesh::messages::GetKnownMeshNodes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::GetKnownMeshNodes >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::MeshNodeSummary*
Arena::CreateMaybeMessage< ::herald::mesh::messages::MeshNodeSummary >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::MeshNodeSummary >(arena);
}
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::KnownMeshNodes*
Arena::CreateMaybeMessage< ::herald::mesh::messages::KnownMeshNodes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::KnownMeshNodes >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
