// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: herald/mesh/messages/models.proto

#include "herald/mesh/messages/models.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace herald {
namespace mesh {
namespace messages {
PROTOBUF_CONSTEXPR Presence::Presence(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mac_)*/uint64_t{0u}
  , /*decltype(_impl_.rssi_)*/0
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PresenceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PresenceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PresenceDefaultTypeInternal() {}
  union {
    Presence _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PresenceDefaultTypeInternal _Presence_default_instance_;
}  // namespace messages
}  // namespace mesh
}  // namespace herald
static ::_pb::Metadata file_level_metadata_herald_2fmesh_2fmessages_2fmodels_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmodels_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_herald_2fmesh_2fmessages_2fmodels_2eproto = nullptr;

const uint32_t TableStruct_herald_2fmesh_2fmessages_2fmodels_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Presence, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Presence, _impl_.mac_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Presence, _impl_.rssi_),
  PROTOBUF_FIELD_OFFSET(::herald::mesh::messages::Presence, _impl_.status_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::herald::mesh::messages::Presence)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::herald::mesh::messages::_Presence_default_instance_._instance,
};

const char descriptor_table_protodef_herald_2fmesh_2fmessages_2fmodels_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!herald/mesh/messages/models.proto\022\024her"
  "ald.mesh.messages\"\222\001\n\010Presence\022\013\n\003mac\030\001 "
  "\001(\004\022\014\n\004rssi\030\002 \001(\005\0225\n\006status\030\003 \001(\0162%.hera"
  "ld.mesh.messages.Presence.Status\"4\n\006Stat"
  "us\022\014\n\010OBSERVED\020\000\022\016\n\nIDENTIFIED\020\001\022\014\n\010VANI"
  "SHED\020\002B\002H\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto = {
    false, false, 218, descriptor_table_protodef_herald_2fmesh_2fmessages_2fmodels_2eproto,
    "herald/mesh/messages/models.proto",
    &descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_herald_2fmesh_2fmessages_2fmodels_2eproto::offsets,
    file_level_metadata_herald_2fmesh_2fmessages_2fmodels_2eproto, file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmodels_2eproto,
    file_level_service_descriptors_herald_2fmesh_2fmessages_2fmodels_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto_getter() {
  return &descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_herald_2fmesh_2fmessages_2fmodels_2eproto(&descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto);
namespace herald {
namespace mesh {
namespace messages {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Presence_Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto);
  return file_level_enum_descriptors_herald_2fmesh_2fmessages_2fmodels_2eproto[0];
}
bool Presence_Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Presence_Status Presence::OBSERVED;
constexpr Presence_Status Presence::IDENTIFIED;
constexpr Presence_Status Presence::VANISHED;
constexpr Presence_Status Presence::Status_MIN;
constexpr Presence_Status Presence::Status_MAX;
constexpr int Presence::Status_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Presence::_Internal {
 public:
};

Presence::Presence(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:herald.mesh.messages.Presence)
}
Presence::Presence(const Presence& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Presence* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mac_){}
    , decltype(_impl_.rssi_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.mac_, &from._impl_.mac_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_) -
    reinterpret_cast<char*>(&_impl_.mac_)) + sizeof(_impl_.status_));
  // @@protoc_insertion_point(copy_constructor:herald.mesh.messages.Presence)
}

inline void Presence::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mac_){uint64_t{0u}}
    , decltype(_impl_.rssi_){0}
    , decltype(_impl_.status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Presence::~Presence() {
  // @@protoc_insertion_point(destructor:herald.mesh.messages.Presence)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Presence::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Presence::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Presence::InternalSwap(Presence* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Presence::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto_getter, &descriptor_table_herald_2fmesh_2fmessages_2fmodels_2eproto_once,
      file_level_metadata_herald_2fmesh_2fmessages_2fmodels_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace mesh
}  // namespace herald
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::herald::mesh::messages::Presence*
Arena::CreateMaybeMessage< ::herald::mesh::messages::Presence >(Arena* arena) {
  return Arena::CreateMessageInternal< ::herald::mesh::messages::Presence >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
